services:
    - docker

env:
  global:
    - ON_TRAVIS=true
    - MUTE_LOGS=true
    - WITH_PYTHON_PEP=true
    - IMAGE=qgis/qgis

  matrix:
    - QGIS_IMAGE=samtwesa/qgis-testing-environment-docker:release-3_16
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.8"

branches:
  only:
    - develop

addons:
  apt:
    packages:
      - git
      - python-software-properties

before_install:
  - docker pull ${QGIS_IMAGE}

install:
  - pip install --upgrade pip
  - pip install --upgrade pep8
  - pip install --upgrade flake8
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e WITH_PYTHON_PEP=${WITH_PYTHON_PEP} -e ON_TRAVIS=${ON_TRAVIS} -e MUTE_LOGS=${MUTE_LOGS} -e DISPLAY=:99 ${QGIS_IMAGE}
  - sleep 10
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh stream_feature_extractor"

  - docker exec -it qgis-testing-environment sh -c "rm -f  /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor"
  - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/ /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor"

script:
  - docker exec -it qgis-testing-environment sh -c "ls /tests_directory"
  - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh test_suite.test_package"
  - make pep8