name: Test on QGIS 3.16

on:
  - pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build docker image
        working-directory: ./
        shell: bash
        env:
          DEFAULT_BRANCH: develop
        run: |
          docker pull samtwesa/qgis-testing-environment-docker:release-3_16
          ./run-docker-test.sh