name: Test on QGIS 3.16

on:
  - pull_request

jobs:
  ci:
    name: Test on CI
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build docker image
        working-directory: ./
        shell: bash
        env:
          DEFAULT_BRANCH: develop
        run:
          docker pull samtwesa/qgis-testing-environment-docker:release-3_16
          pip install --upgrade pip
          pip install --upgrade pep8
          pip install --upgrade flake8

          docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e WITH_PYTHON_PEP=${WITH_PYTHON_PEP} -e ON_TRAVIS=${ON_TRAVIS} -e MUTE_LOGS=${MUTE_LOGS} -e DISPLAY=:99 ${QGIS_IMAGE}
          sleep 10
          docker exec -it qgis-testing-environment sh -c "qgis_setup.sh stream_feature_extractor"

          docker exec -it qgis-testing-environment sh -c "rm -f  /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor"
          docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/ /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/stream_feature_extractor"

          docker exec -it qgis-testing-environment sh -c "ls /tests_directory"
          docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh test_suite.test_package"
          make pep8